#!/usr/bin/env python3
"""
Interactive configuration helper for ansible-guacamole.

This does NOT install anything. It asks a handful of plain-language questions —
crucially *which authentication method* you want — and writes a ready-to-use
host_vars file. You then run the playbook normally:

    python3 scripts/configure.py
    ansible-playbook -i inventory/hosts.ini site.yml

Every answer maps 1:1 to a variable documented in docs/CONFIGURE.md. Re-run it
any time to regenerate the file; it never touches a running system.

Stdlib only — no pip installs, no Ansible required to run this.
"""

from __future__ import annotations

import datetime
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)


# --------------------------------------------------------------------------- io
def ask(prompt: str, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default not in (None, "") else ""
    while True:
        raw = input(f"{prompt}{suffix}: ").strip()
        if raw:
            return raw
        if default is not None:
            return default
        print("  (a value is required)")


def ask_bool(prompt: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{d}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes", "true", "1")


def ask_choice(prompt: str, options: list[tuple[str, str]], default: str) -> str:
    print(f"\n{prompt}")
    for key, desc in options:
        marker = "*" if key == default else " "
        print(f"  {marker} {key:<9} — {desc}")
    valid = {k for k, _ in options}
    while True:
        raw = input(f"choose [{default}]: ").strip().lower() or default
        if raw in valid:
            return raw
        print(f"  pick one of: {', '.join(sorted(valid))}")


def yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if s == "":
        return '""'
    if any(c in s for c in ':#{}[]&*!|>%@`"') or s != s.strip():
        return '"' + s.replace('"', '\\"') + '"'
    return s


def emit(lines: list[str], key: str, value, indent: int = 0) -> None:
    lines.append(" " * indent + f"{key}: {yaml_scalar(value)}")


# ---------------------------------------------------------------------- prompts
def main() -> int:
    print(__doc__)
    print("=" * 70)

    out: list[str] = []
    out.append("---")
    out.append(f"# Generated by scripts/configure.py on {datetime.date.today().isoformat()}")
    out.append("# Safe to hand-edit; see docs/CONFIGURE.md for every option.")
    out.append("")

    # --- host / TLS -------------------------------------------------------
    fqdn = ask("Guacamole hostname (FQDN users browse to)", "guacamole.example.com")
    emit(out, "guac_proxy_site", fqdn)

    tls = ask_choice(
        "TLS certificate for the reverse proxy",
        [
            ("selfsigned", "self-signed now (swap for a real cert later)"),
            ("letsencrypt", "Let's Encrypt (public DNS + port 80 reachable)"),
        ],
        "selfsigned",
    )
    if tls == "letsencrypt":
        emit(out, "guac_tls_mode", "letsencrypt")
        emit(out, "guac_le_dns_name", fqdn)
        emit(out, "guac_le_email", ask("  Let's Encrypt account email", "admin@" + fqdn.split(".", 1)[-1]))
    else:
        emit(out, "guac_tls_mode", "self-signed")
    out.append("")

    # --- database ------------------------------------------------------------
    db = ask_choice(
        "Where does the Guacamole database live",
        [
            ("local", "install MariaDB on this host"),
            ("remote", "use a separate MySQL/MariaDB server"),
        ],
        "local",
    )
    if db == "remote":
        emit(out, "guac_install_mariadb", False)
        emit(out, "guac_mysql_host", ask("  DB host", "db.example.com"))
        emit(out, "guac_mysql_port", int(ask("  DB port", "3306")))
        emit(out, "guac_db_name", ask("  DB name", "guacamole_db"))
        emit(out, "guac_db_user", ask("  DB user", "guacamole_user"))
        emit(out, "guac_db_password", ask("  DB password", secret=True))
        print("  NOTE: create the DB + user + load schema on the remote server, or")
        print("        set guac_db_bootstrap=true with admin creds. See docs/CONFIGURE.md.")
    else:
        emit(out, "guac_db_password", ask("Database password to set for guacamole_user",
                                          "ChangeMe_" + os.urandom(4).hex()))
    out.append("")

    # --- PRIMARY AUTH METHOD ----------------------------------------------
    method = ask_choice(
        "PRIMARY authentication method (who proves the user's identity)",
        [
            ("database", "usernames/passwords stored in Guacamole's own DB"),
            ("ldap", "LDAP / Active Directory bind"),
            ("openid", "OpenID Connect (Keycloak, Entra ID, Okta, Google, ...)"),
            ("saml", "SAML 2.0 (ADFS, Entra ID, Okta, Shibboleth, ...)"),
            ("ssl", "X.509 client certificate / smart card"),
            ("cas", "CAS (Apereo)"),
        ],
        "database",
    )
    out.append(f"# Primary auth: {method}")

    if method == "ldap":
        emit(out, "guac_ldap_enabled", True)
        out.append("guac_ldap:")
        emit(out, "hostname", ask("  LDAP host(s)", "dc1.example.com"), 2)
        emit(out, "port", int(ask("  LDAP port (389 plain / 636 ssl)", "389")), 2)
        emit(out, "encryption_method", ask("  encryption (none|ssl|starttls)", "none"), 2)
        emit(out, "username_attribute", ask("  username attribute", "sAMAccountName"), 2)
        emit(out, "search_bind_dn", ask("  search bind DN", "svc-guac@example.com"), 2)
        emit(out, "search_bind_password", ask("  search bind password", secret=True), 2)
        emit(out, "config_base_dn", ask("  config base DN", "dc=example,dc=com"), 2)
        emit(out, "user_base_dn", ask("  user base DN", "OU=Users,DC=example,DC=com"), 2)
        emit(out, "user_search_filter", ask("  user search filter", "(objectClass=user)"), 2)
        emit(out, "max_search_results", 200, 2)
        if ask_bool("  map LDAP groups for RBAC?", False):
            emit(out, "group_base_dn", ask("  group base DN", "OU=Groups,DC=example,DC=com"), 2)
            emit(out, "member_attribute", "member", 2)
            emit(out, "member_attribute_type", "dn", 2)
            emit(out, "group_name_attribute", "cn", 2)

    elif method == "openid":
        emit(out, "guac_openid_enabled", True)
        out.append("guac_openid:")
        emit(out, "authorization_endpoint", ask("  authorization endpoint URL"), 2)
        emit(out, "jwks_endpoint", ask("  JWKS endpoint URL"), 2)
        emit(out, "issuer", ask("  issuer"), 2)
        emit(out, "client_id", ask("  client ID"), 2)
        emit(out, "redirect_uri", ask("  redirect URI", f"https://{fqdn}/"), 2)
        emit(out, "username_claim_type", ask("  username claim", "email"), 2)
        emit(out, "groups_claim_type", ask("  groups claim", "groups"), 2)
        emit(out, "scope", ask("  scope", "openid email profile"), 2)

    elif method == "saml":
        emit(out, "guac_saml_enabled", True)
        out.append("guac_saml:")
        md = ask("  IdP metadata URL (blank to enter idp_url + entity_id instead)", "")
        emit(out, "idp_metadata_url", md, 2)
        if not md:
            emit(out, "idp_url", ask("  IdP base URL"), 2)
            emit(out, "entity_id", ask("  this SP's entity ID", f"https://{fqdn}/"), 2)
        emit(out, "callback_url", ask("  callback URL", f"https://{fqdn}/"), 2)
        emit(out, "group_attribute", ask("  group attribute", "groups"), 2)
        emit(out, "strict", True, 2)

    elif method == "ssl":
        emit(out, "guac_ssl_auth_enabled", True)
        cert_domain = ask("  cert-verifying hostname", f"cert.{fqdn}")
        emit(out, "guac_ssl_auth_domain", cert_domain)
        emit(out, "guac_ssl_auth_manage_nginx", True)
        ca_path = ask("  path to the client-issuing CA PEM file", "./client-ca.pem")
        try:
            with open(os.path.expanduser(ca_path), "r", encoding="utf-8") as fh:
                ca = fh.read().strip()
            out.append("guac_ssl_auth_client_ca: |")
            for ln in ca.splitlines():
                out.append("  " + ln)
        except OSError:
            print(f"  (could not read {ca_path} — leaving guac_ssl_auth_client_ca blank, fill it in)")
            emit(out, "guac_ssl_auth_client_ca", "")
        out.append("guac_ssl_auth:")
        emit(out, "auth_uri", f"https://{cert_domain}/", 2)
        emit(out, "primary_uri", f"https://{fqdn}/", 2)
        emit(out, "subject_username_attribute", ask("  cert subject attr -> username", "CN"), 2)

    elif method == "cas":
        emit(out, "guac_cas_enabled", True)
        out.append("guac_cas:")
        emit(out, "authorization_endpoint", ask("  CAS server URL", "https://cas.example.com/cas"), 2)
        emit(out, "redirect_uri", ask("  redirect URI", f"https://{fqdn}/"), 2)

    out.append("")

    # --- MFA (stacks on top of the primary method) ----------------------
    mfa = ask_choice(
        "Multi-factor authentication (layers on top of the primary method)",
        [
            ("none", "no second factor"),
            ("totp", "TOTP authenticator app (Google Authenticator, Aegis, ...)"),
            ("duo", "Duo Security push"),
        ],
        "none",
    )
    if mfa == "totp":
        emit(out, "guac_totp_enabled", True)
    elif mfa == "duo":
        emit(out, "guac_duo_enabled", True)
        out.append("guac_duo:")
        emit(out, "api_hostname", ask("  Duo API hostname", "api-XXXXXXXX.duosecurity.com"), 2)
        emit(out, "integration_key", ask("  integration key"), 2)
        emit(out, "secret_key", ask("  secret key", secret=True), 2)
        emit(out, "application_key", ask("  application key (40+ random chars)", os.urandom(20).hex()), 2)
    out.append("")

    # --- optional extras ----------------------------------------------------
    emit(out, "guac_quickconnect_enabled", ask_bool("Enable quick-connect (ad-hoc connections)?", False))
    emit(out, "guac_histrec_enabled", ask_bool("Enable session recording storage?", False))
    emit(out, "guac_branding_enabled", ask_bool("Enable dark-theme branding?", False))
    out.append("")
    out.append("# Backend targets (RDP/SSH/VNC), groups, users and RBAC go here — see")
    out.append("# docs/SCENARIOS.md for copy-paste examples.")
    out.append("guac_connections: []")
    out.append("guac_connection_groups: []")
    out.append("guac_users: []")
    out.append("guac_user_groups: []")
    out.append("")

    # --- write ------------------------------------------------------------
    dest_dir = os.path.join(REPO, "host_vars")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, f"{fqdn}.yml")
    if os.path.exists(dest) and not ask_bool(f"\n{dest} exists — overwrite?", False):
        print("aborted; nothing written.")
        return 1
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")

    print("\n" + "=" * 70)
    print(f"wrote {dest}")
    print("\nNext:")
    print(f"  1. add '{fqdn}' to inventory/hosts.ini under [guacamole]")
    print("  2. review the file (esp. secrets — consider ansible-vault)")
    print(f"  3. ansible-playbook -i inventory/hosts.ini site.yml -l {fqdn}")
    if method in ("openid", "saml", "cas"):
        print(f"\n  Remember to register redirect/callback https://{fqdn}/ with your IdP.")
    if method == "ssl":
        print("\n  Point DNS for the cert hostname (and *.<that host>) at this box, and")
        print("  use a wildcard TLS cert for it in production (see docs/CONFIGURE.md).")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (KeyboardInterrupt, EOFError):
        print("\naborted.")
        sys.exit(130)
