---
- name: Reload systemd guacd
  ansible.builtin.systemd:
    daemon_reload: true
  when: not (guac_container_build | default(false) | bool)

- name: Restart guacd
  ansible.builtin.service:
    name: guacd
    state: restarted
